p8105_hw2_kg3006
================
Kevin Guzman
2025-09-28

## Load Libraries

These are all the libraries for this homework assigment

``` r
library(tidyverse)
```

    ## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
    ## ✔ dplyr     1.1.4     ✔ readr     2.1.5
    ## ✔ forcats   1.0.1     ✔ stringr   1.5.2
    ## ✔ ggplot2   4.0.0     ✔ tibble    3.3.0
    ## ✔ lubridate 1.9.4     ✔ tidyr     1.3.1
    ## ✔ purrr     1.1.0     
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()
    ## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

``` r
library(readxl)
```

## Probelm 1

Problem 1 uses the FiveThirtyEight data which we will need to upload the
pols-month.csv, unempoloyment.csv, and snp.csv. Goal is to merge into a
single dataframe using year and month as keys. \###Cleaning
pols-month.csv \#### Load the data

``` r
pols_month <- 
  read_csv("./fivethirtyeight_datasets/pols-month.csv")
```

    ## Rows: 822 Columns: 9
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl  (8): prez_gop, gov_gop, sen_gop, rep_gop, prez_dem, gov_dem, sen_dem, r...
    ## date (1): mon
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

Has 9 variables, mon is date, others are all numeric.

#### Separating Date into year, month, date

Current structure is “YYYY-MM-DD”, we will separate into year, month,
day. Also will remove the day variable in this step

``` r
pols_month <- 
  pols_month %>%
  separate(col = mon,
           into = c("year", "month", "day"),
           sep = "-") %>% 
  select(-day)
```

#### Changing month from numeric

replacing variables in month from numeric value 1-12, to it’s
corresponding month.

``` r
pols_month <- 
  pols_month %>%
  mutate(month = case_when(
    month == "01" ~ "January",
    month == "02" ~ "February",
    month == "03" ~ "March",
    month == "04" ~ "April",
    month == "05" ~ "May",
    month == "06" ~ "June",
    month == "07" ~ "July",
    month == "08" ~ "August",
    month == "09" ~ "September",
    month == "10" ~ "October",
    month == "11" ~ "November",
    month == "12" ~ "December"
  ))
```

#### Create a “president” variable

Creating a new variable “president” based on prez_gop if 1==gop, and
prez_dem if 1=dem. and removing prez_dem and prez_gop.

``` r
pols_month <- 
  pols_month %>%
  mutate(president = case_when(
    prez_gop == 1 ~ "gop",
    prez_dem == 1 ~ "dem"
  )) %>%
  select(-prez_gop, -prez_dem)
```

### Cleaning snp.csv

#### Load the data

``` r
snp <- 
  read_csv("./fivethirtyeight_datasets/snp.csv")
```

    ## Rows: 787 Columns: 2
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (1): date
    ## dbl (1): close
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

There are two variables here. The first is the date which needs to be
cleaned and go to the front, and the second is the close, which is the
closing value fo the S&P 500 index.

#### Separating Date into year, month, date

Current structure is “M/D/YY”, we will seperate into year, month, day
and remove day. Also making year come first then month

``` r
snp <- 
  snp %>%
  separate(col = date,
           into = c("month", "day", "year"),
           sep = "/") %>%
  select(-day) %>% 
  select(year, month, everything()) 
```

##### Chaning month from numeric to month name

``` r
snp <- 
  snp %>%
  mutate(month = case_when(
    month == "1" ~ "January",
    month == "2" ~ "February",
    month == "3" ~ "March",
    month == "4" ~ "April",
    month == "5" ~ "May",
    month == "6" ~ "June",
    month == "7" ~ "July",
    month == "8" ~ "August",
    month == "9" ~ "September",
    month == "10" ~ "October",
    month == "11" ~ "November",
    month == "12" ~ "December"
  ))
```

##### Year needs to match prior

Year here has 2 digits, need to make it 4 digits to match prior
dataframes by adding 19 to characters 50 - 99 and 20 to characters 00 -
25.

``` r
snp <- 
  snp %>%
  mutate(year = case_when(
    as.integer(year) >= 50 ~ paste0("19", year),
    as.integer(year) <= 25 ~ paste0("20", year)
  ))
```

### Cleaning unemployment.csv

#### Load the data

``` r
unemployment <-
  read_csv("./fivethirtyeight_datasets/unemployment.csv")
```

    ## Rows: 68 Columns: 13
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (13): Year, Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

There are 13 columns, the first is Year which is numeric and needs to
change to character

#### Changing Year

Changing from numeric to character

``` r
unemployment <-
  unemployment %>%
  mutate(Year = as.character(Year))
```

It also needs to be renamed from Year to year to match other dataframes

``` r
unemployment <-
  unemployment %>%
  rename(year = Year)
```

### Changing month

Month data representes the percent of unepolyment in each month. This
will need to be pivoted from wide to long format for month

``` r
unemployment <-
  unemployment %>%
  pivot_longer(cols = Jan:Dec,
               names_to = "month",
               values_to = "unemployment_rate")
```

I will also need to chagne month from shorten 3 word name to full name

``` r
unemployment <-
  unemployment %>%
  mutate(month = case_when(
    month == "Jan" ~ "January",
    month == "Feb" ~ "February",
    month == "Mar" ~ "March",
    month == "Apr" ~ "April",
    month == "May" ~ "May",
    month == "Jun" ~ "June",
    month == "Jul" ~ "July",
    month == "Aug" ~ "August",
    month == "Sep" ~ "September",
    month == "Oct" ~ "October",
    month == "Nov" ~ "November",
    month == "Dec" ~ "December"
  ))
```

### Merging all three dataframes

Now that all three dataframes are cleaned, we can merge them using year
and month as keys with left_join

``` r
merged_data <-
  pols_month %>%
  left_join(snp, by = c("year", "month")) %>%
  left_join(unemployment, by = c("year", "month"))
```

### Description of datasets

This combined dataset contines information gathered from the
FiveThirtyEight data. Each dataset is arranged into year of month of the
data. The pols_month dataset was informative in the party affiliation of
the president in power during each year-month time interval. It also
contains infomration on the number of senators, representitives, and
governers during this time period. The snp dataset contains each
year-month closing value of the S&P 500 index, and finally the
unempolymenbt dataset contains the unemployment rate for each year-month
time interval.

The **dimentions of the dataset** are 822 observations and 11
variables/columns.

**Key variables include**:  
- year  
- month  
- president  
- close (S&P 500 closing value)  
- unemployment_rate

The dataset **starts on 1947 and ends in 2015**.

## Problem 2

In this problem we use the excel file 2024_09_Trash_Wheel_Data.xlsx
which as 3 sheets of importance “Mr. Trash Wheel”, “Professor Trash
Wheel”, and “Gwynnda Trash Wheel”. We will clean each sheet seperately
and then merge.

### Loading Mr. Trashweel data

Specification include cleaning column names, removing columns that are
missing, removing rows without dumpsters, adding dataset for merging,
reorganizing, and making sport balls into integers.

In addition there seems to be a problem in the datasets formating.  
- year - all should be character  
-

``` r
mr_trash_wheel <- 
  read_excel("./Trash/2024_09_Trash_Wheel_Data.xlsx",
                     sheet = "Mr. Trash Wheel") %>% 
  select(-...15, -...16) %>% 
  janitor::clean_names() %>% 
  mutate (dataset="mr_trash_wheel") %>% 
  select(year, month, dataset, everything()) %>% 
  filter(!is.na(dumpster)) %>% 
  mutate(sports_balls = as.integer(round(sports_balls)))
```

    ## New names:
    ## • `` -> `...15`
    ## • `` -> `...16`

### Loading Professor Trash Wheel data

Column names here need to be cleaned, there are no additional variables
that are added too so we don’t have to remove those columns. There is
also no sports balls, so we don’t have to create that step

``` r
professor_trash_wheel <-
  read_excel("./Trash/2024_09_Trash_Wheel_Data.xlsx",
                     sheet = "Professor Trash Wheel") %>% 
  janitor::clean_names() %>% 
  mutate (dataset="professor_trash_wheel") %>%
  select(year, month, dataset, everything()) %>%
  filter(!is.na(dumpster)) %>% 
  mutate(year = as.character(year))
```

### Loading Gwynnda Trash Wheel data

Similar here, no additional columns created and there is no sports ball
variable to mutate.

``` r
gwynnda_trash_wheel <-
  read_excel("./Trash/2024_09_Trash_Wheel_Data.xlsx",
                     sheet = "Gwynnda Trash Wheel") %>% 
  janitor::clean_names() %>% 
  mutate (dataset="gwynnda_trash_wheel") %>%
  select(year, month, dataset, everything()) %>%
  filter(!is.na(dumpster)) %>% 
  mutate(year = as.character(year))
```

All data has month, year dumpster. We will go through each one and then
merge by month and year.

### Join rows for all datasets

Joining all datasets by rows

``` r
trash_wheel_data <-
  bind_rows(mr_trash_wheel,
            professor_trash_wheel,
            gwynnda_trash_wheel)
```

### Description of dataset

This combined dataset contains information on the amount of trash
collected by three different trash wheels in Baltimore. There are a
**total** of 1033 observations and 15 variables/columns. The key
variables include:  
- year  
- month  
- dataset (which trash wheel)  
- dumpster (number of dumpsters collected)  
- plastic_bottles  
- plastic_bags  
- sports_balls (only for Mr. Trash Wheel)

The dataset starts on 2014 and ends in 2024. There are 651 observations
from Mr. Trash Wheel, 119 observations from Professor Trash Wheel, and
263 observations from Gwynnda Trash Wheel.

The **total weight of trash collected by professor trash wheel** was
4.9348^{5} pounds. In addition, the **total number of cigarettes butts
collected by Gwynnda in June of 2022** was 1.812^{4} butts.

## Problem 3 Zillow

We will be using zillow data here

### Loading the data

Uploading the data and cleaning the names with janitor

``` r
zillow_zip <-
  read_csv("./Zillow/Zip Codes.csv") %>% 
  janitor::clean_names()
```

    ## Rows: 322 Columns: 7
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (4): County, County Code, File Date, Neighborhood
    ## dbl (3): State FIPS, County FIPS, ZipCode
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

This dataset contains 7 variables and 322 observations.

``` r
Zori <-
  read_csv("./Zillow/Zip_zori_uc_sfrcondomfr_sm_month_NYC.csv") %>% 
  janitor::clean_names()
```

    ## Rows: 149 Columns: 125
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr   (6): RegionType, StateName, State, City, Metro, CountyName
    ## dbl (119): RegionID, SizeRank, RegionName, 2015-01-31, 2015-02-28, 2015-03-3...
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

149 observations with 125 variables. Most variables are dates with long
format

### Stating to Clean

We are specifically analyzing NYC between Janurary 2015 and August 2024.

#### Cleaning zillow_zip

##### County

First we look at data

``` r
table(zillow_zip$county) # 149 New York, 48 Kings, 30 Bronx, Queens 81, Richmond 14 
```

    ## 
    ##    Bronx    Kings New York   Queens Richmond 
    ##       30       48      149       81       14

``` r
any(is.na(zillow_zip$county)) # No missing values
```

    ## [1] FALSE

There are no missing data.

##### State FIPS

Looking at the data: Will change state to New York if 36

``` r
table(zillow_zip$state_fips) # not a useful data and os will remove 
```

    ## 
    ##  36 
    ## 322

``` r
any(is.na(zillow_zip$state_fips)) # No missing values
```

    ## [1] FALSE

``` r
zillow_zip <- zillow_zip %>% 
  mutate(state_fips = case_when(
     state_fips == 36 ~ "New York",
     TRUE ~ as.character(state_fips)
  ))
```

There are no missing values and all are New York

##### County_code

Looking at county code

``` r
table(zillow_zip$county_code) # not a useful data and os will remove
```

    ## 
    ## 005 047 061 081 085 
    ##  30  48 149  81  14

``` r
any(is.na(zillow_zip$county_code)) # No missing values
```

    ## [1] FALSE

``` r
table(zillow_zip$county_code, zillow_zip$county) # all unique)
```

    ##      
    ##       Bronx Kings New York Queens Richmond
    ##   005    30     0        0      0        0
    ##   047     0    48        0      0        0
    ##   061     0     0      149      0        0
    ##   081     0     0        0     81        0
    ##   085     0     0        0      0       14

All counties match up wtih the county code, this is a redundent
variables so I will remove it.

``` r
zillow_zip <- zillow_zip %>%
  select(-county_code)
```

##### County_fips

Looking at county fips

``` r
table(zillow_zip$county_fips) # not a useful data and os will remove
```

    ## 
    ## 36005 36047 36061 36081 36085 
    ##    30    48   149    81    14

``` r
any(is.na(zillow_zip$county_fips)) # No missing values
```

    ## [1] FALSE

``` r
table(zillow_zip$county_fips, zillow_zip$county) # all unique
```

    ##        
    ##         Bronx Kings New York Queens Richmond
    ##   36005    30     0        0      0        0
    ##   36047     0    48        0      0        0
    ##   36061     0     0      149      0        0
    ##   36081     0     0        0     81        0
    ##   36085     0     0        0      0       14

All counties match up wtih the county fips, this is a redundent
variables so I will remove it.

``` r
zillow_zip <- zillow_zip %>%
  select(-county_fips)
```
